default:
  serverbase:       'http://hapi.fhir.org/baseR4/'
  hospital_name:    'Your Center'
  hospital_zip:     'Center Zip Code'

# if you need to authenticate on your fhir server, set username and password
  username:         ''
  password:         ''
  
# Addition of a common data directory  
  cracked_result:   data/cracked_result.csv
  distance_result:  data/distance_result.csv
  
# Results of aggregation script
  aggregation1_op:  data/aggregation1.csv
  aggregation2_op:  data/aggregation2.csv
  aggregation3_op:  data/aggregation3.csv 
  aggregation4_op:  data/aggregation4.csv  
  aggregation5_op:  data/aggregation5.csv 
  aggregation6_op:  data/aggregation6.csv 
  aggregation7_op:  data/aggregation7.csv 

# if you need to use a proxy server (e.G. http://proxy:port )
  http_proxy:       ''
  https_proxy:      ''
