version: '3.7'

services:
  cord_hackathon:
    build:
      context: .
    image: ghcr.io/chris-ti-an-g/cord_hackathon:012
    restart: unless-stopped
    ports:
      - "3838:3838"
    volumes:
      - ./config:/srv/shiny-server/config:ro
      # - ./data/cracked_result.csv:/srv/shiny-server/data/cracked_result.csv:ro # workaround fuer das umgehen falls die standorte hatte die cracked_result.csv datei nicht aus FHIR server erhalten z.B., aus SQL aufbaut. Der FHIRCrackR-Strecke Umweg
      # - ./data/cracked_result.csv:/srv/shiny-server/data/cracked_result.csv:ro
      # - ./data/distance_result.csv:/srv/shiny-server/data/distance_result.csv:ro
      # - ./data/aggregation1.csv:/srv/shiny-server/data/aggregation1.csv:ro
      # - ./data/aggregation2.csv:/srv/shiny-server/data/aggregation2.csv:ro
      # - ./data/aggregation3.csv:/srv/shiny-server/data/aggregation3.csv:ro
      # - ./data/aggregation4.csv:/srv/shiny-server/data/aggregation4.csv:ro
      # - ./data/aggregation5.csv:/srv/shiny-server/data/aggregation5.csv:ro
      # - ./data/aggregation6.csv:/srv/shiny-server/data/aggregation6.csv:ro
      # - ./data/aggregation7.csv:/srv/shiny-server/data/aggregation7.csv:ro
    environment:
      no_proxy: 'localhost,127.0.0.1'
