version: '3.7'

services:
  cord_hackathon:
    image: ghcr.io/chris-ti-an-g/cord_hackathon:011
    restart: unless-stopped
    ports:
    - "3838:3838"
    volumes:
      - ./config:/srv/shiny-server/config:ro
      # - ./data/cracked_result.csv:/srv/shiny-server/data/cracked_result.csv:ro # workaround fuer das umgehen der FHIRCrackR-Strecke
