version: '3.7'

services:
  cord_hackathon:
    image: ghcr.io/chris-ti-an-g/cord_hackathon:011
    restart: unless-stopped
    ports:
    - "3838:3838"
    volumes:
      - ./config:/srv/shiny-server/config:ro
    environment:
      no_proxy: 'localhost,127.0.0.1'